apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
  labels:
    app: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin 
    spec:
      containers:
      - name: admin
        image: eldokan.azurecr.io/laradokan-admin:latest
        ports:
        - containerPort: 80